behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.001
      beta: 0.009
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 2048
      num_layers: 20
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.5
    keep_checkpoints: 15
    max_steps: 30000000
    time_horizon: 2048
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
