behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0005
      beta: 0.01
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.973
        strength: 0.7
    keep_checkpoints: 2
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 100000
      team_change: 200000
      swap_steps: 2000
      window: 50
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
